### ISSUE TITLE
Response status code does not indicate success: 400 (Bad Request) on Azure

### ISSUE THREAD

**Issue by KarateJB** [Microsoft/Cognitive-LUIS-Windows#31]
When I calls LUIS api with the following code on Azure
`var ret = await lc.Predict(activity.Text);`

There is an error 
> Response status code does not indicate success: 400 (Bad Request)

But the LUIS api response correctly with  Bot framework Channel emulator or thru uri 
`https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/{id}?subscription-key={key}&timezoneOffset=0.0&verbose=true&q=XXXX`

Here is my Cognitive Api setting in Azure 
![](https://4.bp.blogspot.com/-X6Ss69Ti6xM/WO2n6r0zjtI/AAAAAAAAEbc/LJbDxJKysSgeEwaY1vp500VbazoSezg9gCLcB/s1600/azure%2Bsetting.png)

Exception tracestack

```
2017-04-12T03:54:47  PID[4792] Error       Response status code does not indicate success: 400 (Bad Request).
2017-04-12T03:54:47  PID[4792] Error       Source : System.Net.Http
2017-04-12T03:54:47  PID[4792] Error       StackTrace :    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Cognitive.LUIS.HttpClientRestExtensions.<RestGet>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Cognitive.LUIS.LuisClient.<Predict>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LotoBot.Rest.Controllers.MsgController.<createLuisReplyMsg>d__2.MoveNext()
```

Appreciate any help and suggestion, thank you very much!

**Comment by KarateJB** [comment]
My mistake, the LUIS api is ok after I correct the wrong LUIS APP id and key.

**Comment by oleg-bronzhaiev** [comment]
My problem "400 (Bad Request)" was solved by publishing an app as "Production" Endpoint slot.

**Comment by sanjeevgaut** [comment]
> My problem "400 (Bad Request)" was solved by publishing an app as "Production" Endpoint slot.

@oleg-bronzhaiev Thanks. I have changed as production while publishing luis app. 
 It helped and issue gone.
